manifestVersion: subsquid.io/v0.1
name: gs-stats-kusama
version: 3
description: |-
  Giant Squid Stats squid for kusama chain
build:

deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: kusama
    cmd: [ "node", "lib/main" ]
  api:
    cmd: [ "npx", "squid-graphql-server", "--dumb-cache", "in-memory", "--dumb-cache-ttl", "1000", "--dumb-cache-size", "100", "--dumb-cache-max-age", "1000" ]

scale:
  addons:
     postgres:
         storage: 10G

